# Generated by Django 3.1.5 on 2021-01-08 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('cid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('detail', models.TextField(verbose_name='内容')),
                ('cdisry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Diary', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '日记本',
                'verbose_name_plural': '日记本',
                'db_table': 'my_diary',
            },
        ),
    ]
