# Generated by Django 3.1.5 on 2021-01-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
